sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
before_install:
- echo "before_install"
- echo $VIRTUAL_ENV
- export PATH="$HOME/miniconda/bin:$PATH"
- df -h
- date
- pwd
- uname -a
- python -V
- free -m
- ulimit -a
- git --version
- git tag
- pip install --upgrade pip
#- pip install codecov coverage flake8  # ?
install:
- echo "install start"
- pip install -r requirements.txt
#- python setup.py install
#- python setup.py develop
#- make all
script:
- echo "script"
- pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
#- coveralls
notifications:
  email:
    recipients:
    - francis.odonovan@gmail.com
  slack:
    secure: PDtcvz//in9jj9g96rjAePhb59NizHGxrPZpmVXvYLNuYh2iN4i9GgBruLoySS5pg4cALgs69quof9c6lF8U75w0FfcOxfANb+6Y5Joh/uvR7IhPe9rZjadsXG4kNlSwfTcxMOc9mTHmyKi50WcnwWGVjPAU8uKnlUPxV3K3kjeuKD6QDOJuCtKgTKyeW92VvtMAKILBD+UOrkdr72eCwtQ+cReQ2JNgYndRgjcs6TxDRAq2OISrHSyX7/ISfqvHcOCnH8jazSFYbYcTZ7Sk9CnDGt+FDz+e8hNysI5T8sFGge6eiwyJQ7ivqdvbWYKS0AFeJA8BQwbrA7gt6jLaM5v5WLY7npVMAhkwtM2s6/Z2p1IsEqhaigoLINfyBw6MCbIDeZg1OJdocuWRNE+pfZgVXzC2XXcnbg+u5ChaqgqoKqN3/Y+W0IGZ4AXXWcT1XHVgB414j4TZ+t/bIlKMbcdD4n9tvmV9+zm+bZ8keFkWlMSac4bW7wX9gOQG4FMUGolznTinwlAwpCpjP22gM7M6BoDwg2URWE5qcXoJYERHdsvaOAOTlj3RnnBjsVZwbIfk2gbWmE0aKwk8l21PBhjiBsZvHPyBR6EeAUi8bktQUfdAImk53h0GYPeSJ6ocu8fas8NgBuZf5Ysc0RxQYnQUkqZZBO53BOScDr87tHE=
