approvals:
#  by default, an approval is the thumbs up emoji only: ^:\\+1:$
   pattern: "^(:\\+1:|👍)$"

#   by default, every pull request requires two approvals
   minimum: 1

#   by default, the pull request opener can approve its own pull request
#   uncomment this line to ignore approvals from the pull request opener
#   (there is also `last_committer` and `both`)
#   ignore: pr_opener

#   by default, zappr counts everyone as a valid approver
#   uncomment these lines to change it to only collaborators
#   (you can also specify `orgs` and `users` and define `groups`)
#   from:
#     collaborators: true

#autobranch:
#  pattern: {number}-{title}
#  length: 60

#commit:
#  message:
#    patterns: # commit message has to match any one of
#      - "^#[0-9]+" # starts with hash and digits
#      - "^[A-Z]+-[0-9]+" # starts with uppercase letters, a dash and digits

specification:
  title: # title requirements AND body AND template requirements have to match
    minimum-length: # PR title is at least this many characters long
      enabled: true
      length: 8
  body:
    # either of these verifications has to be true
    # PR body is at least this many characters long
    minimum-length:
      enabled: true
      length: 8
    # contains a link - default is false
    contains-url: false
    # contains an issue number - default is false
    contains-issue-number: false
  template:
     # is different from pull request body
     differs-from-body: true

#pull-request:
#  labels:
#    # pull request cannot be merged without these labels
#    required:
#      - reviewed
#    # allow additional labels to be present. true is the default..
#    additional: true
