---
# https://github.com/actions/labeler

name: Labeler
# yamllint disable-line rule:truthy
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
